### PR TITLE
Return in addition property chain of result(s)

### PR DESCRIPTION
**Pull request by Miklet**
Hello,

I've reimplemented current solution a little but kept it compatible without making breaking changes, but I wonder if we couldnt make it a default behaviour to return property chains. Since only your (@kentcdodds) projects are using it.

Cheers.

#1

### CODE REVIEW

**Comment by kentcdodds** [comment]
Yeah, I'd be good with a breaking change here to change the default (or maybe even the only) API.

**Comment by Miklet** [comment]
Ok, I cleaned up code to support minimum Node 4, updated README and tests.

**Review by kentcdodds — APPROVED** [review]
Looks great to me. Thanks!

**Comment by kentcdodds** [comment]
This has been released as v1.0.0!

**Comment by kentcdodds** [comment]
jkjk, spoke too soon... I thought I had publish privileges, but don't...

@rowanoulton, could you publish it? Totally find if you're not interested in maintaining this. Could you give me publish privileges? Otherwise we could probably just take this code and put it into the `nps` repo...

**Comment by rowanoulton** [comment]
@kentcdodds on it!

**Comment by rowanoulton** [comment]
Published 1.0.0 to npm. Cheers to you both!

**Comment by rowanoulton** [comment]
@kentcdodds I've added you as a collaborator of this module on npm which I think (?) gives you publish privileges. Let me know if there's anything more I can do to help.

**Comment by kentcdodds** [comment]
Cool! Thanks a bunch! 👏

**Pull request merged**
